name: Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  rails:
    name: Rails build
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      SECRET_KEY_BASE_DUMMY: "1"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Check routes
        run: ruby bin/rails routes

      - name: Precompile assets
        run: ruby bin/rails assets:precompile

  docker:
    name: Docker image build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
